apiVersion: {{ .Values.mgmt.gitops.openshift_gitops_api_version }}
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: cluster-app-project
  namespace: {{ .Values.mgmt.gitops.ztp_instance_ns }}
spec:
  clusterResourceWhitelist:
  - group: 'hive.openshift.io'
    kind: ClusterImageSet
  - group: 'cluster.open-cluster-management.io'
    kind: ManagedCluster
  - group: ''
    kind: Namespace
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Namespace
  - group: ''
    kind: Secret
  - group: 'extensions.hive.openshift.io'
    kind: ImageClusterInstall
  - group: 'metal3.io'
    kind: DataImage
  - group: siteconfig.open-cluster-management.io
    kind: ClusterInstance
  - group: secrets.hashicorp.com
    kind: VaultStaticSecret
  sourceRepos:
  - '*'

