---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-ztp-git-secret
  namespace: ztp
spec:
  type: kv-v2 
  mount: {{ .Values.mgmt.vault.vault_engine }}
  path: preprod/{{ splitList "-" .Values.mgmt.cluster.name | first }}/gitops/06_gitSecret
  destination:
    name: git-creds
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/default