apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  namespace: multicluster-engine
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  # OSImageCACertRef:
  #   name: http-server-ca
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    storageClassName: "{{ .Values.mgmt.storage.default_storageclass }}"
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: "{{ .Values.mgmt.storage.default_storageclass }}"
  # mirrorRegistryRef:
  #   name: mirror-registry-config-map
  osImages:
    - openshiftVersion: "4.20"
      url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.20.0/rhcos-4.20.11-x86_64-live-iso.x86_64.iso
      rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.20.0/rhcos-4.20.11-x86_64-live-rootfs.x86_64.img
      # pick version from https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.20.0/release.txt
      version: 9.6.20250925-0
      cpuArchitecture: "x86_64"
