apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-mirror
spec:
  releaseImage: "quay.apps.{{ .Values.mgmt.cluster.name }}.{{ .Values.mgmt.cluster.domain }}/ocp/openshift/release-images:4.18.28-x86_64"
