apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: my-lvm-cluster
  namespace: openshift-lvm-storage
spec:
  storage:
    deviceClasses:
      - default: true
        deviceSelector:
          forceWipeDevicesAndDestroyAllData: true
          paths:
            - /dev/sdb # TBR per cluster
        fstype: xfs
        name: data-lab-vg1
        thinPoolConfig:
          chunkSizeCalculationPolicy: Static
          metadataSizeCalculationPolicy: Host
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
        # nodeSelector:
        #   nodeSelectorTerms:
        #     - matchExpressions:
        #         - key: kubernetes.io/hostname
        #           operator: In
        #           values:
        #             # - master1.example.com
